### ISSUE TITLE
Eliminar la carpeta master-media

### ISSUE THREAD

**Issue by jorgerdc** [jorgerdc/tutoriales#42]
@alexJava2015 De favor, podrías crear un branch para eliminar esta carpeta ?
Se que habíamos platicado de crear un branch para las imágenes.  Esta idea no resultó ser tan buena.  Ha funcionado mejor poner las imágenes dentro del mismo directorio donde se encuentra el documento que las ocupa. Esto facilita la documentación y nos evitamos poner rutas largas en los MD.   Actualiza de favor los documentos que tengas con imágenes dentro de este branch.

**Comment by alexJava2015** [comment]
Se realizo el ajuste solicitado, se elimina carpeta, los documentos con imágenes aun no los subo, realizare lo que comentas.

**Comment by jorgerdc** [comment]
Este issue fue ya resuelto a través de un PR. Por lo que veo, no se realizó la asociación para cerrarlo de forma automática. Se realiza de forma manual.
